### ISSUE TITLE
Please add links to Redmine and the necessary emacs packages

### ISSUE THREAD

**Issue by ndokos** [kametoku/orgmine#1]
That would make it easier for potential users to evaluate your package and also make it easier to install if they so choose.

**Comment by kametoku** [comment]
As described in README.org, the following packages are required for orgmine.el.
You can install these packages from MELPA.
- elmine
- s

**Comment by ndokos** [comment]
What I suggested was that a lot of people (well, maybe just me) would like to look at the packages _before_ installing them. I know what s is (and I have it installed), I don't know what elmine is (although I can guess) and I have no idea what Redmine is (although I can google). But making the links available in your README would enhance the attraction of your project.

**Comment by kametoku** [comment]
Thank you for the feedback. I understand your suggestion.
Updated README.org with links to Redline, ermine and s.

**Comment by kametoku** [comment]
OK. I am closing the issue. If there are other comments, please submit new issue. Thanks.
