### ISSUE TITLE
Error after load

### ISSUE THREAD

**Issue by bimawa** [kametoku/orgmine#3]
First thanks a lot for this awesome package! 
And i have strage error: 
`File mode specification error: (void-variable orgmine-tag-refile-me)`
Maybe i'm something wrong setup?

**Comment by kametoku** [comment]
I guess the setup of `orgmine-tags` is not correct and found that the sample in README.org was wrong.
Please have a look at the revised sample setup of `orgmine-tags` in README.org.

Note that you don't have to setup `orgmine-tags` by yourself if you prefer to the default tags of orgmine such as `CREATE_ME`.

**Comment by bimawa** [comment]
@kametoku Yea thanks a lot! I'm remove override `orgmine-tags`, and now work all! Thanks!
