### ISSUE TITLE
Dedline not work

### ISSUE THREAD

**Issue by bimawa** [kametoku/orgmine#4]
Sorry for issue but when i'm setup deadline on issue :om_due_date: not update.

**Comment by kametoku** [comment]
It works as designed.

`C-c C-d` (`org-deadline`) updates the DEADLINE property of an issue but does not update :om_due_date: property.

When submitting the change to Redmine server and the issue has both of DEADLINE and :om_due_date: properties, orgmine reads the value of DEADLINE property and update issue's due date by that value (ignoring :om_due_date: value).
The value of :om_due_date: property will be automatically updated then.

**Comment by bimawa** [comment]
I'm try submit it, but orgmine told me: no need to submit update.

**Comment by kametoku** [comment]
Please try C-u prefix. It will force to submit the update.
Adding UPDATE_ME tag to the headline is another resolution.

**Comment by bimawa** [comment]
@kametoku Yeaaa work it! 👍  Thanks  a lot Tokuya!
