### ISSUE TITLE
Do you support clocksum?

### ISSUE THREAD

**Issue by bimawa** [kametoku/orgmine#5]
@kametoku Sorry for distrib, but orgmine support clocksum? For update time_entries in Redmine.

*Freezed*
Tasks:

- [ ] Add support clocksum 
- [ ] And sync with Redmine `time_entries`

**Comment by kametoku** [comment]
No. orgmine does not support time entries in Redmine.
Time clocking of org-mode is kept locally, no sync with time entries in Redmine.

**Comment by bimawa** [comment]
It's feature is open for pull request?

**Comment by kametoku** [comment]
Yes. Any pull request would be welcome!

**Comment by bimawa** [comment]
Ok Thanks you, for you orgmine. if i find enough of time i think about it. I'm close this issue for now.
