### ISSUE TITLE
Want example by `custom-fields`

### ISSUE THREAD

**Issue by bimawa** [kametoku/orgmine#6]
Guys do you support `custom-fields` array? If yes, can you describe how use it?

**Comment by kametoku** [comment]
Custom fields are **experimentally** implemented.
You can view and edit a custom field via :om_cf_ID_NAME: property, where ID is the id of the custom field and NAME is the name of the custom fields.

Let's say you have a custom field "Resolution" and its id is 1.
You will see the value of the custom field as :om_cf_1_Resolution: property of an issue if a value is assigned to the field for the issue.

    ** Closed xxx
      :PROPERTIES:
      :om_cf_3_resolution: fixed
      ...
      :END:

TIPS:
Run `orgmine-insert-template` at the bottom of the orgmine buffer, it will insert settings for the given Redmine project.

**Comment by bimawa** [comment]
I have this errors on custom fileds parser: `user-error: Invalid property name: "om_cf_82_Номер сборки"` and `orgmine-insert-template` not insert this field in template header. Maybe its related with spacebars in fields?

**Comment by bimawa** [comment]
Yea i'm check it, spaces didn't work in custom fields.

- [x] Needs fix parsing custom fields with space between words in name.

**Comment by kametoku** [comment]
Thank you for the report. Pull the latest revision and try it.

**Comment by bimawa** [comment]
Yea its work now, but not clear solution. All my custom fields in Cyrillic was escaped:

```
:om_cf_1_%D0%92%D0%B0%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C: 50
:om_cf_82_%D0%9D%D0%BE%D0%BC%D0%B5%D1%80%20%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B8: 1.16.13

```

mb can we add something like <kbd>/</kbd> to escape space, and not only it?

**Comment by kametoku** [comment]
Thank you for spotting the side effect. Now fixed.

**Comment by bimawa** [comment]
@kametoku Thanks a lot! now only space letter escaped. 
`:om_cf_82_Номер%20сборки: 1.16.13`
i'll try test it
