### ISSUE TITLE
Attachment upload failed

### ISSUE THREAD

**Issue by lin-yeyiqi** [kametoku/orgmine#9]
Hi,
I wanted to upload an attachment to redmine with orgmine, but I kept reporting errors. 
Can someone help me?

The following is the error message.
`
Will you update entry #1619? (y or n) y
let*: Wrong number of arguments: (lambda (method path data params) "Perform a raw HTTP request with given METHOD, a relative PATH and a
plist of PARAMS for the query." (let* ((redmine-host (if (boundp (quote redmine-host)) redmine-host elmine/host)) (redmine-api-key (if (boundp (quote redmine-api-key)) redmine-api-key elmine/api-key)) (url (elmine/api-build-url path params)) (url-request-method method) (url-request-extra-headers (list (quote ("Content-Type" . "application/json")) (cons "X-Redmine-API-Key" redmine-api-key))) (url-request-data data) header-end status header body) (save-excursion (switch-to-buffer (url-retrieve-synchronously url)) (beginning-of-buffer) (setq header-end (save-excursion (if (re-search-forward "^$" nil t) (progn (forward-char) (point)) (point-max)))) (if (re-search-forward "^HTTP/\\(1\\.0\\|1\\.1\\) \\([0-9]+\\) \\([A-Za-z ]+\\)$" nil t) (progn (setq status (plist-put status :code (string-to-number (match-string 2)))) (setq status (plist-put status :text (match-string 3))))) (while (re-search-forward "^\\([^:]+\\): \\(.*\\)" header-end t) (setq header (cons (match-string 1) (cons (match-string 2) header)))) (if (eq header-end (point-max)) nil (setq body (url-unhex-string (buffer-substring header-end (point-max))))) (kill-buffer)) (list (quote :status) status (quote :header) header (quote :body) body))), 5
mwheel-scroll: End of buffer [5 times]
`

**Comment by kametoku** [comment]
Hi @lin-yeyiqi, please pull the latest code and give it try. Thanks!!

**Comment by lin-yeyiqi** [comment]
> Hi @lin-yeyiqi, please pull the latest code and give it try. Thanks!!

Thank you for your help.The attachment can be uploaded.
